name: MarkdownLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Markdown files
      uses: DavidAnson/markdownlint@v0.23.0
